### ISSUE TITLE
Support complex matrices?

### ISSUE THREAD

**Issue by ssfrr** [baggepinnen/TotalLeastSquares.jl#6]
I'm not sure if the underyling algorithm is amenable to supporting complex matrices. If so do you think it's an easy add to the package? Currently it throws an error trying to get `eps(::Complex)`

MWE:

```julia
u = randn(ComplexF64, 100)
v = randn(ComplexF64, 20)
D = u*v' .+ randn.(ComplexF64) .* 0.1
A, E, s, sv = rpca(D)
```

**Comment by baggepinnen** [comment]
I have not considered complex matrices, but there is not reason not to allow them right away! I'll have a look and see what we can do

**Comment by baggepinnen** [comment]
The following now works on ~master~ v1.3.1
```julia
           u = randn(ComplexF64, 100)
            v = randn(ComplexF64, 20)
            E = randn(ComplexF64,100,20) .* 10 .* (rand.() .< 0.01)
            A = u*v'
            D = A .+ E
            Ah, Eh, s, sv = rpca(D)
            @test sum(abs2, Eh-E)/sum(abs2, E) < 1e-5
            @test sum(abs2, Ah-A)/sum(abs2, A) < 1e-5
```
I had to find a replacement for the soft thresholding operator for complex numbers, the following seems to work okay but not much thought has gotten into it
```julia
@inline function soft_th(x::Complex, ϵ)
    m,a = abs(x), angle(x)
    m = max(m-ϵ,zero(m)) + min(m+ϵ,zero(m))
    m*cis(a)
end
```

**Comment by ssfrr** [comment]
Great, thanks! I’ll try it out and see if this improves things over regular PCA for my problem.
